/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,jsx}',
  ],
  safelist: [
    { pattern: /grid-cols-(1|2|3|4|5|6|12)/, variants: ['md', 'lg', 'sm'] },
    { pattern: /col-span-(1|2|3|4|5|6|7|8|9|10|11|12)/, variants: ['md', 'lg'] },
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#23005c',
        'secondary-container': '#571bc1',
        'error-container': '#93000a',
        'error': '#ffb4ab',
        'on-surface-variant': 'var(--on-surface-variant)',
        'surface-container': 'var(--surface-container)',
        'primary': '#E8313F',
        'inverse-on-surface': '#313030',
        'tertiary-container': '#41a447',
        'on-primary-container': '#ffffff',
        'primary-container': '#E8313F',
        'on-tertiary-fixed': '#002204',
        'on-tertiary': '#00390a',
        'surface-variant': 'var(--surface-variant)',
        'on-primary-fixed-variant': '#93001a',
        'primary-fixed': '#E8313F',
        'inverse-primary': '#be0726',
        'on-secondary-container': '#c4abff',
        'surface-dim': 'var(--bg)',
        'outline-variant': 'var(--outline-variant)',
        'secondary-fixed': '#e9ddff',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-bright': 'var(--surface-bright)',
        'on-error': '#690005',
        'on-primary-fixed': '#410006',
        'surface-container-high': 'var(--surface-container-high)',
        'on-tertiary-container': '#003208',
        'surface-tint': '#E8313F',
        'surface': 'var(--bg)',
        'primary-fixed-dim': '#E8313F',
        'surface-container-highest': 'var(--surface-container-highest)',
        'on-tertiary-fixed-variant': '#005313',
        'background': 'var(--bg)',
        'on-surface': 'var(--text)',
        'on-secondary': '#3c0091',
        'secondary': '#d0bcff',
        'outline': 'var(--outline)',
        'tertiary-fixed': '#94f990',
        'on-primary': '#ffffff',
        'tertiary': '#78dc77',
        'secondary-fixed-dim': '#d0bcff',
        'surface-container-low': 'var(--surface-container-low)',
        'tertiary-fixed-dim': '#78dc77',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#5516be',
        'inverse-surface': 'var(--text)',
        'on-background': 'var(--text)',
        'brand-red': '#E8313F',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'section-padding': '40px',
        'bento-gap': '12px',
        'gutter': '16px',
        'container-margin': '24px',
      },
      fontFamily: {
        'display-lg': ['Hanken Grotesk'],
        'body-sm': ['Inter'],
        'display-lg-mobile': ['Hanken Grotesk'],
        'label-mono': ['JetBrains Mono'],
        'headline-md': ['Hanken Grotesk'],
        'body-md': ['Inter'],
        'stat-lg': ['Hanken Grotesk'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '900' }],
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0em', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '900' }],
        'label-mono': ['12px', { lineHeight: '1.2', letterSpacing: '0.12em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'stat-lg': ['32px', { lineHeight: '1.0', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
}