version: '3.8'

services:
  db:
    image: postgres:15
    container_name: visionfit_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: visionfit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: visionfit_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:123@db:5432/visionfit
    depends_on:
      - db

volumes:
  postgres_data: