"""ilk_semayi_olustur

Revision ID: 3bee5fd6b69a
Revises: 
Create Date: 2026-06-15 08:09:00.078813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bee5fd6b69a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=255), nullable=False),
    sa.Column('soyad', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('sifre', sa.String(length=255), nullable=False),
    sa.Column('boy', sa.Float(), nullable=True),
    sa.Column('kilo', sa.Float(), nullable=True),
    sa.Column('yas', sa.Integer(), nullable=True),
    sa.Column('cinsiyet', sa.String(length=20), nullable=True),
    sa.Column('aktiflik_seviyesi', sa.String(length=30), nullable=True),
    sa.Column('hedef', sa.String(length=30), nullable=True),
    sa.Column('email_dogrulandi', sa.Boolean(), nullable=False),
    sa.Column('dogrulama_token', sa.String(length=100), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ogun_tipi', sa.String(length=20), nullable=False),
    sa.Column('besin_anahtari', sa.String(length=50), nullable=False),
    sa.Column('besin_adi', sa.String(length=100), nullable=False),
    sa.Column('gram', sa.Float(), nullable=False),
    sa.Column('kalori', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('karbonhidrat_g', sa.Float(), nullable=False),
    sa.Column('yag_g', sa.Float(), nullable=False),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_logs_id'), 'meal_logs', ['id'], unique=False)
    op.create_table('step_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('adim_sayisi', sa.Integer(), nullable=False),
    sa.Column('aktivite_tipi', sa.String(length=30), nullable=False),
    sa.Column('yakilan_kalori', sa.Float(), nullable=False),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_logs_id'), 'step_logs', ['id'], unique=False)
    op.create_table('water_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('miktar_ml', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_logs_id'), 'water_logs', ['id'], unique=False)
    op.create_table('workout_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hareket_adi', sa.String(), nullable=True),
    sa.Column('eminlik_skoru', sa.Float(), nullable=True),
    sa.Column('diz_acisi', sa.Integer(), nullable=True),
    sa.Column('antrenor_notu', sa.String(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_history_hareket_adi'), 'workout_history', ['hareket_adi'], unique=False)
    op.create_index(op.f('ix_workout_history_id'), 'workout_history', ['id'], unique=False)
    op.create_table('workout_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('hareket', sa.String(length=100), nullable=False),
    sa.Column('set_sayisi', sa.Integer(), nullable=True),
    sa.Column('tekrar_sayisi', sa.Integer(), nullable=True),
    sa.Column('agirlik', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_notes_id'), 'workout_notes', ['id'], unique=False)
    op.create_index(op.f('ix_workout_notes_tarih'), 'workout_notes', ['tarih'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_notes_tarih'), table_name='workout_notes')
    op.drop_index(op.f('ix_workout_notes_id'), table_name='workout_notes')
    op.drop_table('workout_notes')
    op.drop_index(op.f('ix_workout_history_id'), table_name='workout_history')
    op.drop_index(op.f('ix_workout_history_hareket_adi'), table_name='workout_history')
    op.drop_table('workout_history')
    op.drop_index(op.f('ix_water_logs_id'), table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_index(op.f('ix_step_logs_id'), table_name='step_logs')
    op.drop_table('step_logs')
    op.drop_index(op.f('ix_meal_logs_id'), table_name='meal_logs')
    op.drop_table('meal_logs')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
